name: bakar_scraper.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5,17 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode proyek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python & Selenium
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager bs4 requests pandas undetected-chromedriver

      - name: Jalankan Scraper Sakti
        run: python run_all.py

      - name: Simpan Data Terbaru ke Web
        run: |
          git config --global user.name 'GoTrans Bot'
          git config --global user.email 'bot@gotrans.com'
          git add .
          git commit -m "[Automated] Update jadwal.json" || echo "Tidak ada perubahan data."
          git pull --rebase origin main
          git push origin main
